version: '3.8'

services:
  jobmanager:
    image: flink:1.14.2
    container_name: jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: jobmanager

  taskmanager:
    image: flink:1.14.2
    container_name: taskmanager
    hostname: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    command: taskmanager
    depends_on:
      - jobmanager

networks:
  default:
    external:
      name: flink_network